% Configuration version. Needs to match the major version number of the toolbox
CONFIG_VERSION = '3';

% PROGRAM DEFAULTS
% while you can set all the measurement parameters here, you really
% shouldn't. Only set as default parameters that are unlikely to change
% (i.e. that are part of your set-up or intrinsic properties of your sample
DEFAULT_PARAMETERS = {...
%           '<parameter>', <value>; ...
            'tunepicscaling', 6.94e4; ... % MHz/<tunepicunit>
            'S', 1/2; ...                 % sample spin
            'maxpwr', 0.2; ...            % bridge max power (W)
            'savemat', false; ...         % save results as a .mat file
            'rgain', 1; ...               % files are normalised wrt receiver gain 
            'nscans', 1; ...              % dito number of scans
            'tc', 1; ...                  % dito time constant
           };

% TUNE FILES
% list of known extensions for loading dialog
TUNE_FORMATS = {...
%               '*.<extension1>, *.<extension2>', '<description>', '<loadfunction>'; ...
                '*.sct', 'sc tune file (*.sct)', 'LoadSCFormat'; ...
                '*.csv; *.CSV', 'Tektronix TDS2002C files (*.csv, *.CSV)', 'LoadTektronixCSV'; ...
                '*.mat', 'MatLab file (*.mat)', 'LoadMat'; ...
                '*.png; *.PNG', 'Image file (*.png)', 'LoadImage'; ...
                '*','All Files (*)', ''; ...
               };


% SPECTRUM FILES
% list of known extensions for filtering in loading dialog
SPECTRUM_FORMATS = {...
%                   '*.<extension1>, *.<extension2>', '<description>'; ...
                    '*.scs', 'sc spectrum file (*.scs)', 'LoadSCFormat'; ...
                    '*.akku; *.akku2; *.dat2; *.ch1; *.ch2', 'dat2 and other FU Berlin files (*.dat2, *.akku, *.akku2, *.ch1, *.ch2)', 'LoadFsc2'; ...
                    '*.xml', 'Magnetec spectrum file (*.xml)', 'LoadMagnetecXML'; ...
                    '*.DTA; *.DSC', 'Bruker Xepr files (*.DTA, *.DSC)', 'LoadBrukerBES3T'; ...
                    '*.mat', 'MatLab file (*.mat)', 'LoadMat'; ...
                    '*','All Files (*)',''; ...
                   };


