% PROGRAM DEFAULTS
% while you can set all the measurement parameters here, you really
% shouldn't. Only set as default parameters that are unlikely to change
% (i.e. that are part of your set-up or intrinsic properties of your sample
DEFAULTS = {...
            'tunepicscaling', 6.94e4; ... % MHz/s
            'S', 1/2; ...                 % sample spin
            'maxpwr', 0.2; ...            % bridge max power (W)
           };

% TUNE FILES
% list of known extensions for loading dialog
TUNE_KNOWN_FORMATS = {...
%                     '*.<extension1>, *.<extension2>', '<description>'; ...
                      '*.sct', 'sc tune file (*.sct)'; ...
                      '*.csv; *.CSV', 'Tektronix TDS2002C files (*.csv, *.CSV)'; ...
                      '*.mat', 'MatLab file (*.mat)'; ...
                      '*','All Files (*)'; ...
                     };

% list of load functions to associate with extension
TUNE_LOADFUNCTIONS = {...
%                     '.<extension>','<function-name>'; ...
                      '.sct','LoadSCFormat'; ...
                      '.csv','LoadTektronixCSV'; ...
                      '.mat','LoadMat'; ...
                     };

% SPECTRUM FILES
% list of known extensions for filtering in loading dialog
SPECTRUM_KNOWN_FORMATS = {...
%                         '*.<extension1>, *.<extension2>', '<description>'; ...
                          '*.scs', 'sc spectrum file (*.scs)'; ...
                          '*.akku; *.akku2; *.dat2; *.ch1; *.ch2', 'dat2 and other FU Berlin files (*.dat2, *.akku, *.akku2, *.ch1, *.ch2)'; ...
                          '*.DTA; *.DSC', 'Bruker Xepr files (*.DTA, *.DSC)'; ...
                          '*.mat', 'MatLab file (*.mat)'; ...
                          '*','All Files (*)'; ...
                         };

% list of load functions to associate with extension.
SPECTRUM_LOADFUNCTIONS = {...
%                         '.<extension>','<function-name>'; ...
                          '.scs','LoadSCFormat'; ...
                          '.akku','LoadFsc2'; ...
                          '.akku2','LoadFsc2'; ...
                          '.dat2','LoadFsc2'; ...
                          '.ch1','LoadFsc2'; ...
                          '.ch2','LoadFsc2'; ...
                          '.DTA','LoadBrukerBES3T'; ...
                          '.DSC','LoadBrukerBES3T'; ...
                          '.mat','LoadMat'; ...
                         };
